---
name: CI

on: [push]

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - name: check ip
        run: ip address
      - uses: actions/checkout@v1
      - name: before_script
        run: |
            sudo apt-get update
            sudo apt-get install -y ansible-lint libssl-dev libffi-dev yamllint
            ansible-lint --version
      - name: befor lint
        run: git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
      - name: lint
        run: |
          ls -la
          yamllint . -c .yamllint
          ansible-lint . -c .ansible-lint
      - name: after lint
        run: rm -rf ~/ansible-lint-rules
  platform_test:
    needs: lint_check
    runs-on: ubuntu-latest
    steps:
      - name: check ip
        run: ip address
      - uses: actions/checkout@v1
      - name: before_script
        run: |
            sudo apt-get update
            sudo apt-get install -y python-pip libssl-dev libffi-dev docker
            sudo pip install --upgrade --user setuptools
      - name: install molecule
        run: |
            sudo pip install molecule
            sudo pip install 'molecule[docker]'
      - name: before_script
        run: |
            rm -rf molecule/resources/provisioning
            ansible --version
            ansible-lint --version
            molecule --version
            git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
      - name: deployment test
        run: molecule test -s default
  platform_test1:
    needs: lint_check
    runs-on: ubuntu-latest
    steps:
      - name: check ip
        run: ip address
      - name: check ip
        run: ping -c3 10.1.0.1 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.2 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.3 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.4 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.5 2>/dev/null
  platform_test2:
    needs: lint_check
    runs-on: ubuntu-latest
    steps:
      - name: check ip
        run: ip address
      - name: check ip
        run: ping -c3 10.1.0.1 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.2 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.3 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.4 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.5 2>/dev/null
  platform_test3:
    needs: lint_check
    runs-on: ubuntu-latest
    steps:
      - name: check ip
        run: ip address
      - name: check ip
        run: ping -c3 10.1.0.1 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.2 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.3 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.4 2>/dev/null
      - name: check ip
        run: ping -c3 10.1.0.5 2>/dev/null
