---
name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # runs-on: docker://leandelivery/docker-ansible-ci:ansible-2.8
    steps:
      # - name: use container
        # uses: docker://leandelivery/docker-ansible-ci:ansible-2.8
        # steps:
      - uses: actions/checkout@v1
      - name: before_script
        run: |
            ls -ll
            sudo apt-get update
            # sudo apt-get remove -y python*
            sudo apt-get install -y ansible-lint python-pip libssl-dev libffi-dev
            # sudo ln -s /usr/bin/python3.6 /usr/bin/python
            # python --version
            python3 --version
            # python3.6 --version
            sudo pip install --upgrade --user setuptools
      - name: install molecule
        run: sudo pip install molecule
      - name: before_script
        run: |
            rm -rf molecule/resources/provisioning
            ansible --version
            ansible-lint --version
            molecule --version
            git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
      - name: befor lint
        run: git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
      - name: lint
        run: |
          ls -la
          yamllint . -c .yamllint
          ansible-lint . -c .ansible-lint
      - name: after lint
        run: rm -rf ~/ansible-lint-rules
      - name: deployment test
        run: molecule test -s default
