---
name: CI

on: [push]

jobs:
  # lint_check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: before_script
  #       run: |
  #           sudo apt-get update
  #           sudo apt-get install -y ansible-lint libssl-dev libffi-dev yamllint
  #           ansible-lint --version
  #     - name: befor lint
  #       run: git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  #     - name: lint
  #       run: |
  #         yamllint . -c .yamllint
  #         ansible-lint . -c .ansible-lint
  #     - name: after lint
  #       run: rm -rf ~/ansible-lint-rules
  # platform_test:
  #   needs: lint_check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: before_script
  #       run: |
  #           sudo apt-get update
  #           sudo apt-get install -y python-pip libssl-dev libffi-dev docker
  #           sudo pip install --upgrade --user setuptools
  #     - name: install molecule
  #       run: |
  #           sudo pip install molecule
  #           sudo pip install 'molecule[docker]'
  #     - name: before_script
  #       run: |
  #           rm -rf molecule/resources/provisioning
  #           ansible --version
  #           ansible-lint --version
  #           molecule --version
  #           git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
  #     - name: deployment test
  #       run: molecule test -s default
  platform_test_aws:
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.aws_secret_access_key}}
      EC2_REGION: 'us-east-1'
      # MOLECULE_DEBUG: true
    # needs: lint_check
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v1
        # with:
        #   ref: develop
      - name: before_script
        run: git clone https://github.com/VadzimKavaleuski/ansible-role-heartbeat.git ./
      - name: before_script
        run: cp -r -v ./add/ ./molecule/resources
      - name: before_script
        run: cat .git/packed-refs
      - name: before_script
        run: |
            sudo apt-get update
            sudo apt-get install -y python-pip libssl-dev libffi-dev
            sudo pip install --upgrade --user setuptools
      - name: install molecule
        run: sudo pip install molecule boto boto3 botocore
      # - name: prepare aws creds
      #   run: |
      #       mkdir .aws
      #       touch .aws/credentials
      #       echo "[default]\n" >>.aws/credentials
      #       echo aws_access_key_id=$aws_access_key_id\n >>.aws/credentials
      #       echo aws_secret_access_key=$aws_secret_access_key\n >>.aws/credentials
      #       cat .aws/credentials
      - name: before_script
        run: |
            rm -rf molecule/resources/provisioning
            ip address
            ansible --version
            ansible-lint --version
            molecule --version
            pip list boto | grep boto
            echo "before ls"
            # git branch
            ls -ll
            # ls -ll molecule
            echo "ls -la molecule "
            ls -la molecule
            echo "ls -la molecule/resources"
            ls -la molecule/resources
            echo "ls -la molecule/resources/provisioning"
            ls -la molecule/resources/provisioning
            echo "after ls"
      - name: deployment test
        run: molecule test -s cloud-aws-direct
  # platform_test_azure:
  #   env:
  #     AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  #     AZURE_SECRET: ${{secrets.AZURE_SECRET}}
  #     AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  #     AZURE_TENANT: ${{secrets.AZURE_TENANT}}
  #     EC2_REGION: 'us-east-1'
  #     # MOLECULE_DEBUG: true
  #   # needs: lint_check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: before_script
  #       run: |
  #           sudo apt-get update
  #           sudo apt-get install -y python-pip libssl-dev libffi-dev
  #           sudo pip install --upgrade --user setuptools
  #     - name: install molecule
  #       run: sudo pip install molecule msrestazure ansible[azure]
  #     - name: before_script
  #       run: |
  #           rm -rf molecule/resources/provisioning
  #           ansible --version
  #           ansible-lint --version
  #           molecule --version
  #           # git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
  #     - name: deployment test
  #       run: molecule test -s cloud-azure-direct
